# This is a basic workflow that is manually triggered

name: Create Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0' # The Go version to download (if necessary) and use.
      - name: workaround
        run: sudo rm /usr/bin/go
      - name: workaround modify PATH 
        run: export PATH=$(GOPATH)/bin:$(PATH) 
      - name: version
        run: go version
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: build server
        run: cd server && go build .
      - name: build cli
        run: cd cli && go build -o phctl .
      - name: add date to release body
        run: "TZ=JST-9 LANG=C date '+- %Y/%m/%d %H:%M:%S %z' >> edge.txt"
      - name: add git commit-id to release body (server)
        run: 'cd server && echo `git log -n 1 --pretty=format:"- server: %H"` >> ../edge.txt'
      - name: add git commit-id to release body (cli)
        run: 'cd cli && echo `git log -n 1 --pretty=format:"- cli: %H"` >> ../edge.txt'
      - name: copy binary to home
        run: cp server/phantasma-flow . && cp cli/phctl .
      - name: create tar.gz
        run: tar czvf phantasma-flow-linux-amd64.tar.gz phantasma-flow phctl README.md
      - name: Pre release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "edge"
          name: "Edge"
          prerelease: true
          body_path: "edge.txt"
          files: phantasma-flow-linux-amd64.tar.gz
